## 1. Ststems of linear equations. Cramer's rule.

### Cramerの公式
$$
    \begin{pmatrix}
    a_{11}  & a_{12} & a_{13} & \cdots & a_{1m}\\
    a_{21}  & a_{22} & a_{23} & \cdots & a_{2m}\\
    & & \cdots & & \\
    a_{m1} & a_{m2} & a_{m3} & \cdots & a_{mm}
    \end{pmatrix}
    \begin{pmatrix}
    x_{1}\\
    x_{2}\\
    \cdots\\
    x_{m}
    \end{pmatrix}
    =
    \begin{pmatrix}
    b_{1}\\
    b_{2}\\
    \cdots\\
    b_{m}
    \end{pmatrix}
$$
連立方程式
$$
    \mathbf{A}\mathbf{x}=\mathbf{b}
$$
が与えられたとき、その解は
$$
    x_{k}=\frac{\mathrm{det}\,\mathbf{A}_{(k)}}{\mathrm{det}\,\mathbf{A}}
$$
によって得られる。

### 余因子展開を用いた行列式の計算
行列式を余因子展開を用いて解くことを考える。

$C_m$が$m \times m$の行列式の計算回数とすると
$$
    C_m = mC_{m-1}
    \\
    \therefore C_m = O(m!)
$$
の計算量となる。
$$
    \left(
    \begin{array}{c|cccc}
    a_{11} & a_{12} & a_{13} & \cdots & a_{1m} \\
    \hline
    a_{21} & a_{22} & a_{23} & \cdots & a_{2m} \\
    a_{31} & a_{32} & a_{33} & \cdots & a_{3m} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    a_{m1} & a_{m2} & a_{m3} & \cdots & a_{mm} \\
    \end{array}
    \right)
$$
$O(m!)$の計算量は非常に大きく、$1\,{\rm Gflop}$(=1秒間に浮動小数点演算を$1\times 10^9$回行うことができる)としても

| $m$  | $m!$                    | &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;time&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;|
| ---- | ----------------------- | ---------------------------------------------------------- |
| $10$ | $ 3.6 \times 10^6 $     | $\simeq3.6\times10^{-3}\,{\rm sec}$                              |
| $20$ | $ 2.4 \times 10^{18} $  | $ \simeq 2.4 \times 10^{9}\,{\rm sec}\hspace{5pt}\simeq760\,{\rm yrs} $     |
| $50$ | $ 3 \times 10^{64} $    | $ \simeq 3 \times 10^{53}\,{\rm sec}\hspace{5pt}\simeq10^{46}\,{\rm yrs} $  |

と$m$が増加するごとに計算量も爆発的に増加してしまう。

## 2. Gaussian elimination.
### 2.1. ガウスの消去法
$m$元連立一次方程式
$$
\begin{cases}
    \begin{align}
        a_{11}x_{1}+a_{12}x{2}+&\cdots+a_{1m}x{m} = b_{1} \\
        a_{21}x_{1}+a_{22}x{2}+&\cdots+a_{2m}x{m} = b_{2} \\
        &\cdots \\
        a_{m1}x_{1}+a_{m2}x{2}+&\cdots+a_{mm}x{m} = b_{m} \\
    \end{align}
\end{cases}
$$
を考える。いま、
$$
    \mathbf{A} = 
    \begin{pmatrix}
    a_{11}  & a_{12} & a_{13} & \cdots & a_{1m}\\
    a_{21}  & a_{22} & a_{23} & \cdots & a_{2m}\\
    & & \cdots & & \\
    a_{m1} & a_{m2} & a_{m3} & \cdots & a_{mm}
    \end{pmatrix}
    \hspace{15pt}(\mathrm{det}\,A\neq0)
$$
とする。ガウスの消去法では、まず行同士の加減演算をして要素0の数を増やすこと(Forward sweep)を目標にする。例えば、行列$\mathbf{A}$の二行一列目を0にすることを考えると$\gamma_{21}=a_{21}/a_{11}$として
$$
    \begin{align}
        a_{11}x_{1}&+a_{12}x_{2}+\cdots+a_{1m}x_{m}=b_{1} \\
        (a_{21}-\gamma_{21}a_{11})x_{1}&+(a_{22}-\gamma_{21}a_{12})x_{2}+\cdots+(a_{2m}-\gamma_{21}a_{1m})x_{m} =b_{2}-\gamma_{21}b_{1} \\
    \end{align}
$$
とすれば良い。同様の操作を3行目からm行目まで行うと、$m-1$回の計算後
$$
    \mathbf{A^{(1)}}\mathbf{x}=\mathbf{b^{(1)}}
$$
が得られる。ここで
$$
    \mathbf{A^{(1)}}=
    \left(
    \begin{array}{c|cccc}
    \times  & \times & \times & \cdots & \times \\
    \hline \\
    0  & \times & \times & \cdots & \times \\
    0 & \times & \times & \cdots & \times \\
    & & \cdots & & \\
    0 & \times & \times & \cdots & \times
    \end{array}
    \right)
$$
である。このようにして得られた2行2列目以降のサイズが$m-1$の正方行列に対しても同様の操作を繰り返していくと
$$
    \begin{pmatrix}
    \times & \times & \times & \cdots & \times & \times \\
    0 & \times & \times & \cdots & \times & \times \\
    0 & 0 & \times & \cdots & \times & \times \\
    \vdots & & & \ddots & \vdots & \vdots \\
    0 & 0 & 0 & \cdots & \times & \times \\
    0 & 0 & 0 & \cdots & 0 & \times \\
    \end{pmatrix}
$$
のような上三角行列が得られる。これをm行目から順々に解いていく(back substitution)と$x_{1},\,x_{2},\cdots,x_{m}$が得られる。

### 2.2. ガウスの消去法の計算量
2.1.での議論を踏まえて、ガウスの消去法の計算量を考える。
- Forward sweep
$$
    \begin{pmatrix}
    a_{11}  & a_{12} & a_{13} & \cdots & a_{1m}\\
    a_{21}  & a_{22} & a_{23} & \cdots & a_{2m}\\
    & & \cdots & & \\
    a_{m1} & a_{m2} & a_{m3} & \cdots & a_{mm}
    \end{pmatrix}
    \begin{pmatrix}
    x_{1}\\
    x_{2}\\
    \cdots\\
    x_{m}
    \end{pmatrix}
    =
    \begin{pmatrix}
    b_{1}\\
    b_{2}\\
    \cdots\\
    b_{m}
    \end{pmatrix}
$$
1列目を2行目以降全て0にすることを考える。\
$i=2 \sim m$(行)について
$$
    p=\frac{a_{11}}{a_{i1}}:\,1{\rm\,division}
$$
を求める。
$j=2 \sim m$(列)について
$$
    a_{ij}=a_{ij}-pa_{1i}:\,m-1\,{\rm times\,multiplication} \\
    b_{i}=b_{i}-pb_{1}:\,1\,{\rm multiplication}
$$
よって、一列目の2行目以降を0にするのに必要な計算量は$(m-1)(m-1+2)$回である。\
同様にして考えると$1$列目から$m-1$列目までの前進消去に必要な計算量は
$$
    \sum_{k=1}^{m-1}(m-k+2)(m-k)
$$
である。
- Back substitution
$$
    \begin{pmatrix}
    a_{11} & a_{12} & a_{13} & \cdots & a_{1m} \\
    0 & a_{22} & a_{23} & \cdots & a_{2m} \\
    0 & 0 & a_{33} & \cdots & a_{3m} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & 0 & \cdots & a_{mm} \\
    \end{pmatrix}
    \begin{pmatrix}
    x_{1} \\
    x_{2} \\
    x_{3} \\
    \vdots \\
    x_{m}
    \end{pmatrix}
    =
    \begin{pmatrix}
    b_{1} \\
    b_{2} \\
    b_{3} \\
    \vdots \\
    b_{m}
    \end{pmatrix}    
$$
未知数$x_{i}$を$x_{m}$から順に求めていくと
$$
    x_{m}=\frac{b_{m}}{a_{mm}}:\,1{\rm\,division} \\
    x_{m-1}=\frac{b_{m-1}-a_{m-1,m}x_{m}}{a_{m-1,m-1}}:\,1{\rm\,division},\,1\,{\rm multiplication} \\
    \vdots \\
    x_{k}=\frac{b_{k}-\sum_{l=k+1}^{m}{a_{kl}x_{l}}}{a_{kk}}:\,1{\rm\,division},\,m-k\,{\rm times\,multiplication} \\
    \vdots \\
    x_{1}=\frac{b_{1}-\sum_{l=2}^{m}{a_{1l}x_{l}}}{a_{11}}:\,1{\rm\,division},\,m-1\,{\rm times\,multiplication}
$$
したがって、この操作で必要な計算回数はそれぞれ
$$
    {\rm division}:\,m\,{\rm times} \\
    {\rm multiplication}:\,\sum_{k=1}^{m-1}(m-k)=\frac{m(m-1)}{2}\,{\rm times}
$$
よって、ガウスの消去法で必要な計算量は
$$
    \sum_{k=1}^{m-1}(m-k+2)(m-k)+m+\frac{m(m-1)}{2}\simeq O(n^3)
$$
となる。

In [1]:
import numpy as np

In [127]:
np.random.seed(2)
size = 5
A = np.float64(np.random.randint(1, 9, (size, size)))
x = np.random.rand(size, 1)
b = np.float64(np.random.randint(1, 9, (size, 1)))

print(A)
print(b)
print("Ax=bの解:\n", np.linalg.solve(A, b))

# 前進消去アルゴリズム
for i in range(len(A) - 1): # 引く行
    for j in range(i+1, len(A)): # 引かれる行
        p = A[j][i] / A[i][i]
        A[j] = A[j] - p * A[i]
        b[j] = b[j] - p * b[i]

# 後退代入アルゴリズム
for k in reversed(range(len(x))):
    x[k] = b[k] / A[k][k]
        
    for l in range(k+1, len(x)):
        x[k] = x[k] - A[k][l] * x[l] / A[k][k]

print(x)

[[1. 8. 6. 1. 7.]
 [4. 3. 4. 1. 8.]
 [3. 2. 8. 4. 6.]
 [8. 8. 8. 3. 5.]
 [5. 5. 6. 8. 4.]]
[[5.]
 [8.]
 [4.]
 [6.]
 [1.]]
Ax=bの解:
 [[ 0.55544841]
 [-0.08293153]
 [-0.03809065]
 [-0.56316297]
 [ 0.84281581]]
[[ 0.55544841]
 [-0.08293153]
 [-0.03809065]
 [-0.56316297]
 [ 0.84281581]]


## 2.3 LU分解
ガウスの消去法では
$$
    \mathbf{A}\mathbf{x}=\mathbf{b} \rightarrow \mathbf{A^{(1)}}\mathbf{x}=\mathbf{b^{(1)}}\hspace{10pt}(\mathbf{A^{(1)}}\,{\rm is\,Upper\,triangular\,matrix.})
$$
というような変形をした。\
<img src="img/matrix.png" alt="行列" title="行列">
ここで上式のように$\gamma$を定め
$$
    \mathbf{\Lambda_{1}}=
    \begin{pmatrix}
    1  & 0 & 0 & \cdots & 0 \\
    -\gamma_{21}  & 1 & 0 & \cdots & 0 \\
    -\gamma_{31} & 0 & 1 & \cdots & 0 \\
    \vdots & \vdots & & \ddots & \\
    -\gamma_{m1} & 0 & 0 & \cdots & 1
    \end{pmatrix}
$$
を考えると、
$$
    \begin{pmatrix}
    1  & 0 & 0 & \cdots & 0 \\
    -\gamma_{21}  & 1 & 0 & \cdots & 0 \\
    -\gamma_{31} & 0 & 0 & \cdots & 0 \\
    \vdots & \vdots & & \ddots & \\
    -\gamma_{m1} & 0 & 0 & \cdots & 1
    \end{pmatrix}
    \begin{pmatrix}
    a_{11} \\
    a_{21} \\
    a_{31} \\
    \vdots \\
    a_{m1}
    \end{pmatrix}
    =
    \begin{pmatrix}
    a_{11} \\
    0 \\
    0 \\
    \vdots \\
    0
    \end{pmatrix}    
$$
であるから、ガウスの前進消去で行なった行列の一列目の変換は、
$$
    \mathbf{\Lambda_{1}Ax}=\mathbf{\Lambda_{1}b}
$$
のように$\mathbf{\Lambda_{1}}$を$\mathbf{Ax}=\mathbf{b}$の左側からかけることに等しい。\
同様に考えると二列目の変換は
$$
    \mathbf{\Lambda_{2}}=
    \begin{pmatrix}
    1  & 0 & 0 & 0 & \cdots & 0 \\
    0  & 1 & 0 & 0 & \cdots & 0 \\
    0 & -\gamma_{32} & 1 & 0 & \cdots & 0 \\
    0 & -\gamma_{42} & 0 & 1 & \cdots & 0 \\
    \vdots & \vdots & \vdots & & \ddots & \\
    0 & -\gamma_{m2} & 0 & 0 & \cdots & 1 \\
    \end{pmatrix}
$$
を$\mathbf{\Lambda_{1}Ax}=\mathbf{\Lambda_{1}b}$の左側からかける操作に等しい。\
したがって、前進消去の操作は
$$
    \mathbf{\Lambda_{m-1}\cdots\Lambda_{1}Ax}=\mathbf{\Lambda_{m-1}\cdots\Lambda_{1}b}
$$
と同じであるから、このようにして得られた上三角行列$\mathbf{\Lambda_{m-1}\cdots\Lambda_{1}A}$を$\mathbf{U}$とすると
$$
\begin{eqnarray*}
    \mathbf{A}&=&\mathbf{(\Lambda_{{\it m}-1}\cdots\Lambda_{1})^{-1}U} \\
    &=&\mathbf{\Lambda_{1}^{-1}\cdots\Lambda_{{\it m}-1}^{-1}}\mathbf{U}
\end{eqnarray*}
$$
となる。\
ここで$\mathbf{\Lambda_{\it k}}$がどのような行列となるかを見てみると、例えば
$$
    \mathbf{\Lambda_{1}^{-1}}=
    \begin{pmatrix}
    1  & 0 & 0 & \cdots & 0 \\
    \gamma_{21}  & 1 & 0 & \cdots & 0 \\
    \gamma_{31} & 0 & 1 & \cdots & 0 \\
    \vdots & \vdots & & \ddots & \\
    \gamma_{m1} & 0 & 0 & \cdots & 1
    \end{pmatrix}
$$
$$
    \mathbf{\Lambda_{2}^{-1}}=
    \begin{pmatrix}
    1  & 0 & 0 & 0 & \cdots & 0 \\
    0  & 1 & 0 & 0 & \cdots & 0 \\
    0 & \gamma_{32} & 1 & 0 & \cdots & 0 \\
    0 & \gamma_{42} & 0 & 1 & \cdots & 0 \\
    \vdots & \vdots & \vdots & & \ddots & \\
    0 & \gamma_{m2} & 0 & 0 & \cdots & 1 \\
    \end{pmatrix}
$$
のようになる。よって、
$$
    \mathbf{\Lambda_{1}^{-1}\Lambda_{2}^{-1}\cdots\Lambda_{{\it m}-1}^{-1}}=
    \begin{pmatrix}
    1  & 0 & 0 & \cdots & 0 \\
    \gamma_{21}  & 1 & 0 & \cdots & 0 \\
    \gamma_{31} & \gamma_{32} & 1 & \cdots & 0 \\
    \vdots & \vdots & & \ddots & \\
    \gamma_{m1} & \gamma_{m2} & \gamma_{m3} & \cdots & 1
    \end{pmatrix}
$$
が得られるから、下三角行列
$$
    \mathbf{L}=
    \begin{pmatrix}
    1  & 0 & 0 & \cdots & 0 \\
    \gamma_{21}  & 1 & 0 & \cdots & 0 \\
    \gamma_{31} & \gamma_{32} & 1 & \cdots & 0 \\
    \vdots & \vdots & & \ddots & \\
    \gamma_{m1} & \gamma_{m2} & \gamma_{m3} & \cdots & 1
    \end{pmatrix}
$$
を用いて行列$\mathbf{A}$は
$$
    \mathbf{A=LU}
$$
と二つの行列の積に分解することができる。\
したがって、$\mathbf{LU}$分解による連立一次方程式$\mathbf{Ax=b}$の解法をまとめると
1. $\mathbf{A=LU}$に分解する
2. 両辺に左側から$\mathbf{L}^{-1}$をかけ、右辺の$\mathbf{L}^{-1}\mathbf{b}$を計算する。
3. $\mathbf{Ux=}\mathbf{L}^{-1}\mathbf{b}$を解く

の3ステップとなる。

## LU分解とピボッティング
$\mathbf{Ax=b}$の解が一意に定まるためには$\mathrm{det}\mathbf{A}\neq0$であることが必要であるが、$\mathbf{LU}$分解ではその計算過程で出てくる全ての小行列式が$0$でないことが要求される。\
また、小行列式が$0$でなかったとしても$0$に非常に近い場合、浮動小数点数の誤差の関係から精度が悪くなる。そこで**ピボット**という操作を考える。
$$
    \mathbf{A} = 
    \begin{pmatrix}
    a_{11}  & a_{12} & a_{13} & \cdots & a_{1m}\\
    a_{21}  & a_{22} & a_{23} & \cdots & a_{2m}\\
    a_{31}  & a_{32} & a_{33} & \cdots & a_{3m}\\
    & & \cdots & & \\
    a_{m1} & a_{m2} & a_{m3} & \cdots & a_{mm}
    \end{pmatrix}
    \hspace{15pt}(\mathrm{det}\,A\neq0)
$$
という行列を前進消去していく過程を考える。まず、1列目に操作を施す際に、1列目で最も絶対値が大きい要素を見つける(この操作の計算量は$O(m)$)。\
例えば$a_{31}$が一列目で最も絶対値が大きい要素である場合、1行目と3行目を入れ替える。この操作を**<span style="color: red; ">部分ピボット選択</span>**という。行だけでなく列までを考えて、1行1列に最も絶対値の大きい要素を持ってくることもあるが、これは**<span style="color: red; ">完全ピボット選択</span>**といい、計算量は$O(m^{2})$である。
### 行列の基本変形

3行3列の行列$\mathbf{A}$の行と列を入れ替える基本変形を考える。
$$
    P_{12} = 
    \begin{pmatrix}
    0 & 1 & 0 \\
    1 & 0 & 0 \\
    0 & 0 & 1 
    \end{pmatrix}
    \hspace{10pt}
    P_{13} = 
    \begin{pmatrix}
    0 & 0 & 1 \\
    0 & 1 & 0 \\
    1 & 0 & 0 
    \end{pmatrix}
    \hspace{10pt}
    P_{23} = 
    \begin{pmatrix}
    1 & 0 & 0 \\
    0 & 0 & 1 \\
    0 & 1 & 0 
    \end{pmatrix}
$$
例えば、$P_{12}\mathbf{A}$のように$P_{12}$を$\mathbf{A}$の左側からかけると$\mathbf{A}$の1行目と2行目が交換される。逆に$\mathbf{A}P_{12}$のように$P_{12}$を$\mathbf{A}$の右側からかけると、$\mathbf{A}$の一列目と二列目が交換される。\
次に、一般化をしてサイズ$m$の行列$\mathbf{A}$を考える。サイズ$m$の単位行列$I_{m}$の$k$行目と$l$行目を入れ替えた行列を$P_{kl}$とすると、$P_{kl}\mathbf{A}$は$\mathbf{A}$の$k$行目と$l$行目を、$\mathbf{A}P_{kl}$は$\mathbf{A}$の$k$列目と$l$列目をそれぞれ入れ替えた行列になる。
### 部分ピボット選択を用いたLU分解
部分ピボット選択を用いて前進消去をすることを考える。\
$k$列目の前進消去をする際に行$i_{k}$の要素の絶対値が最も大きい場合、行列$P_{k,i_{k}}$を$\mathbf{A}$の左側からかけ、その上で$\mathbf{\Lambda_{k}}$を左側からかければ良い。したがって、1列目から順に部分ピボット選択を用いて前進消去をしていくと、
$$
    \begin{eqnarray*}
        \mathbf{Ax}&=&\mathbf{b} \\
        \mathbf{\Lambda_{1}\mathrm{{\it P}_{1}}Ax}&=&\mathbf{\Lambda_{1}\mathrm{{\it P}_{1}}b} \\
        \mathbf{\Lambda_{2}\mathrm{{\it P}_{2}}\Lambda_{1}\mathrm{{\it P}_{1}}Ax}&=&\mathbf{\Lambda_{2}\mathrm{{\it P}_{2}}\Lambda_{1}\mathrm{{\it P}_{1}}b} \\
        \vdots
    \end{eqnarray*}
$$
最終的に、
$$
    \mathbf{A}^{(m-1)}=\mathbf{\Lambda_{\mathrm{{\it m}-1}}\mathrm{{\it P}_{\mathrm{{\it m}-1}}}\cdots\Lambda_{2}\mathrm{{\it P}_{2}}\Lambda_{1}\mathrm{{\it P}_{1}}A}
$$
が得られ、$\mathbf{A}^{(m-1)}$が$\mathbf{LU}$分解をしたときの上三角行列$\mathbf{U}$に当たる。\
一般的に、
$\mathrm{det}\,A\neq0$である行列$\mathbf{A}$に対して、部分ピボット選択を行い$\mathbf{LU}$分解をすると
$$
    \mathbf{A}=P\mathbf{LU}
$$
は一意に定まる。